---
- name: Query Oracle Database Role and Switchover Status
  hosts: ora19cdg01.bwok.org
  tasks:
    - name: Source the bash profile and set environment variables
      shell: |
        # Set Environment Variables
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin

        # Run SQL Query to get database details
        echo "SELECT database_role FROM v\$database;" | sqlplus -s / as sysdba
      register: db_01p
      ignore_errors: yes

    - name: Display database role
      debug:
        msg: "Database role: {{ db_01p.stdout }}"

    - name: Check if database role is PRIMARY
      fail:
        msg: "Process halted because database role is not PRIMARY."
      when: "'PRIMARY' not in db_01p.stdout"

    - name: Process completed successfully
      debug:
        msg: "Database role is PRIMARY. Process completed successfully."
      when: "'PRIMARY' in db_01p.stdout"

- name: Query Oracle Database Role and Switchover Status
  hosts: ora19cdg02.bwok.org
  tasks:
    - name: Source the bash profile and set environment variables
      shell: |
        # Set Environment Variables
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin

        # Run SQL Query to get database details
        echo "SELECT database_role FROM v\$database;" | sqlplus -s / as sysdba
      register: db_02S
      ignore_errors: yes

    - name: Display database role
      debug:
        msg: "Database role: {{ db_02S.stdout }}"

    - name: Check if database role is PHYSICAL STANDBY
      fail:
        msg: "Process halted because database role is not PHYSICAL STANDBY."
      when: "'PHYSICAL STANDBY' not in db_02S.stdout"

    - name: Process completed successfully
      debug:
        msg: "Database role is PHYSICAL STANDBY. Process completed successfully."
      when: "'PHYSICAL STANDBY' in db_02S.stdout"
