---
- name: List files in /home/ansible
  hosts: localhost
  tasks:
    - name: Ensure the directory exists
      ansible.builtin.shell: cd /home/ansible/ | cat database1.csv
      register: db1
      ignore_errors: true

    - name: Display the output
      debug: msg="{{db1.stdout}}"

    - name: "set db standby"
      set_stats:
        data:
          standby1_db:  ""

    - name: "set db standby"
      set_stats:
        data:
          standby_db:  ""

#    - name: Display database role
#      debug:
#        msg: "db1"
#      register: prim
#      when: "'PRIMARY' in db1.stdout"

#    - name: Display database role
#      debug:
#        msg: "db1"
#      register: stby1
#      when: "'PHYSICAL STANDBY' in db1.stdout"

    - name: "set db primary"
      set_stats:
        data:
          primary_db:  "ora19cdg01.bwok.org"
      when: "'PRIMARY' in db1.stdout"

    - name: "set db standby"
      set_stats:
        data:
          standby1_db:  "ora19cdg01.bwok.org"
      when: "'PHYSICAL STANDBY' in db1.stdout"

#########################
    - name: Ensure the directory exists
      ansible.builtin.shell: cd /home/ansible/ | cat database2.csv
      register: db2
      ignore_errors: true

    - name: Display the output
      debug: msg="{{db2.stdout}}"

    - name: "set db standby"
      set_stats:
        data:
          standby2_db:  ""

#    - name: Display database role
#      debug:
#        msg: "db2"
#      register: prim
#      when: "'PRIMARY' in db2.stdout"

#    - name: Display database role
#      debug:
#        msg: "db2"
#      register: stby2
#      when: "'PHYSICAL STANDBY' in db2.stdout"

    - name: "set db primary"
      set_stats:
        data:
          primary_db:  "ora19cdg02.bwok.org"
      when: "'PRIMARY' in db2.stdout"

    - name: "set db standby"
      set_stats:
        data:
          standby2_db:  "ora19cdg02.bwok.org"
      when: "'PHYSICAL STANDBY' in db2.stdout"
#########################
    - name: Ensure the directory exists
      ansible.builtin.shell: cd /home/ansible/ | cat database3.csv
      register: db3

      ignore_errors: true

    - name: Display the output
      debug: msg="{{db3.stdout}}"

    - name: "set db standby"
      set_stats:
        data:
          standby3_db:  ""

#    - name: Display database role
#      debug:
#        msg: "db3"
#      register: prim
#      when: "'PRIMARY' in db3.stdout"

#    - name: Display database role
#      debug:
#        msg: "db3"
#      register: stby3
#      when: "'PHYSICAL STANDBY' in db3.stdout"

    - name: "set db primary"
      set_stats:
        data:
          primary_db:  "ora19cdg03.bwok.org"
      when: "'PRIMARY' in db3.stdout"

    - name: "set db standby"
      set_stats:
        data:
          standby3_db:  "ora19cdg03.bwok.org"
      when: "'PHYSICAL STANDBY' in db3.stdout"
