---
- name: Cek DB1 Primary
  hosts: localhost
  tasks:
    - name: "Tampilkan data dari PRIMARY"
      debug:
        msg: "{{ primary_db }}"
    - name: "Tampilkan data dari STANDBY1"
      debug:
        msg: "{{ standby1_db }}"

    - name: "Tampilkan data dari STANDBY2"
      debug:
        msg: "{{ standby2_db }}"
    - name: "Tampilkan data dari STANDBY3"
      debug:
        msg: "{{ standby3_db }}"

    - name: "Cek apakah primary_db adalah ora19cdg01.bwok.org"
      assert:
        that:
          - primary_db == 'ora19cdg01.bwok.org'
        fail_msg: "Pengecekan gagal: primary_db bukan ora19cdg01.bwok.org"
        success_msg: "Pengecekan berhasil: primary_db adalah ora19cdg01.bwok.org"

    - name: "Cek isi dari STANDBY2 dan STANDBY3"
      assert:
        that:
          - standby2_db | length > 0 or standby3_db | length > 0
        fail_msg: "Pengecekan gagal: baik standby2_db maupun standby3_db kosong"
        success_msg: "Pengecekan berhasil: salah satu dari standby2_db atau standby3_db memiliki isi"
